### ISSUE TITLE
Jetty use with sample app DevelopmentSample?

### ISSUE THREAD

**Issue by jms90h5** [quarks-edge/quarks#25] opened 2016-02-18 02:18 UTC
After dusting off literally decades old java experience I was able to gat a clean build of all the quarks projects on (OSX 10.11.3) and the Hello world application runs fine in Eclipse Mars 4.5.1.  However when I run the DevelopmentSample application I get the error below before the series of '.' start printing in the console. Looking at the code from that particular sample app it's not obvious to what the necessary jetty dependencies are.  Should I have copied something from the quarks distribution to jetty webapps?

---

Feb 17, 2016 7:04:02 PM org.eclipse.jetty.util.log.Log initialized
INFO: Logging initialized @253ms
Feb 17, 2016 7:04:02 PM org.eclipse.jetty.server.Server doStart
INFO: jetty-9.3.6.v20151106
Feb 17, 2016 7:04:02 PM org.eclipse.jetty.server.handler.ContextHandler doStart
INFO: Started o.e.j.s.ServletContextHandler@34ce8af7{/jobs,null,AVAILABLE}
Feb 17, 2016 7:04:02 PM org.eclipse.jetty.server.handler.ContextHandler doStart
INFO: Started o.e.j.s.ServletContextHandler@b684286{/metrics,null,AVAILABLE}
Feb 17, 2016 7:04:02 PM org.eclipse.jetty.webapp.WebInfConfiguration getCanonicalNameForWebAppTmpDir
WARNING: Can't generate resourceBase as part of webapp tmp dir name: java.lang.IllegalStateException: No resourceBase or war set for context
Feb 17, 2016 7:04:02 PM org.eclipse.jetty.webapp.WebAppContext doStart
WARNING: Failed startup of context o.e.j.w.WebAppContext@880ec60{/console,null,null}{}
java.lang.IllegalStateException: No resourceBase or war set for context
    at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:406)
    at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:72)
    at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:480)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:516)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.server.Server.start(Server.java:405)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.Server.doStart(Server.java:372)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at quarks.console.server.HttpServer.startServer(HttpServer.java:90)
    at quarks.providers.development.DevelopmentProvider.<init>(DevelopmentProvider.java:65)
    at quarks.samples.topology.DevelopmentSample.main(DevelopmentSample.java:19)

Feb 17, 2016 7:04:02 PM org.eclipse.jetty.server.AbstractConnector doStart
INFO: Started ServerConnector@643b1d11{HTTP/1.1,[http/1.1]}{0.0.0.0:51600}
Feb 17, 2016 7:04:02 PM org.eclipse.jetty.server.Server doStart
INFO: Started @491ms
http://localhost:51600/console
.................................

**Comment by wmarshall484** [comment] 2016-02-18 03:37
Thanks for the find! @home4slc @ddebrunner Do we produce a WAR file during build that didn't make it into the release for the console?

**Comment by ddebrunner** [comment] 2016-02-18 03:40
I think this is running from loading the git code into Eclipse, not from a release.

**Comment by wmarshall484** [comment] 2016-02-18 05:02
Ah, mistyped. When built on linux, I see that the build uses /tmp/jetty-\* to generate the WAR files, and then zips the WAR to console/webapps/console.war.

When running from Eclipse after cloning, the above output is seen:

```
WARNING: Can't generate resourceBase as part of webapp tmp dir name: java.lang.IllegalStateException: No
resourceBase or war set for context
```

There is no war file generated, and there seems to be some issue with setting the resource base which causes the stacktrace.

**Comment by ddebrunner** [comment] 2016-02-18 14:24
The issue is that the war file is only built by Ant.
When loaded into Eclipse it's just building Java code.

I guess the expected pattern for **using** the development console is you are using a release and building your own Quarks applications, not development of Quarks itself.

If anyone can provide a pull request that builds the war when using Eclipse it would be welcomed though.

**Comment by jms90h5** [comment] 2016-02-18 14:53
Hi Dan,

So my initial plan was to use ant to build all various Quarks artifacts first, and then use the convenience of Eclipse to experiment with the various (java) sample applications such as HelloWorld and DevelopmentSample.  After the ant build I do have a ./target/java8/console/webapps/console.war file but that doesn't seem to get picked up when running the Quarks application(s) from within Eclipse.

If Eclipse is only intended to be used to develop Quarks itself and not Quarks applications, could you perhaps point me to some documentation that describes the preferred (non-eclipse) way to write java programs that use Quarks?

**Comment by dlaboss** [comment] 2016-02-18 14:59
A workaround that @vdogaru came up with for running a DevelopmentProvider based app in Eclipse was:

```
$ cd <quarks-home>
$ ant clean all
$ cp -R target/java8/console/webapps .
```

**Comment by dlaboss** [comment] 2016-02-18 15:23
woops, that `cd` above was supposed to be ``cd <quarks-home>``

**Comment by jms90h5** [comment] 2016-02-18 15:23
Ahhh. That worked.  

Although as a point of clarification where I had to put copy the webapps folder containing the console.war file was in the root of the eclipse workspace.

**Comment by dlaboss** [comment] 2016-02-18 15:28
yeah, I botched the markdown on the `cd`. sorry for the confusion.

**Comment by home4slc** [comment] 2016-02-18 18:26
I'll try to get this working for both Eclipse and from the command line.  So far my attempts are a see-saw battle - I can get it running from within Eclipse and not the command line and vice versa.

**Comment by s-a-mcintyre** [comment] 2016-02-18 21:46
One solution would be to add an Ant Builder to the Project. Right-click the project, choose Properties..., select Builders, click New..., choose Ant Builder, and in the dialog that comes up, select Browse Workspace to choose the build.xml from the workspace to populate the buildfile field on the Main tab, then choose the Targets tab and select the Auto Build field to have the default target 'ungrey' so that the default target runs after every change. The only annoying thing perhaps is that it grabs the console window anytime you edit a source file. Although, you could just leave Manual Build selected and remember to run Build All or Clean when you want the .war file.

**Comment by home4slc** [comment] 2016-02-19 18:14
I just committed merge request #34 for this.  You can now run console applications from eclipse, with the caveat that console.war must be present.
There is an error thrown if it is not present.
@s-a-mcintyre (Andrew?? :-) ) I tried to do what you said, but I was getting errors during compilation in the console/servlets package.  I chose the default target 'all', to no avail.
@jms90h5 can you try to run the example from Eclipse now and tell me your results?
If you are successful I'll close this issue.

**Comment by home4slc** [comment] 2016-02-22 19:17
Can anyone else verify it works to run eclipse applications that use DevelopmentProvider?  I'd like to close this issue.  Reminder - console.war must be present under the webapps directory.

**Comment by jms90h5** [comment] 2016-02-22 19:19
Works fine now for me.  Thanks.

**Comment by home4slc** [comment] 2016-02-22 19:19
Thanks @jms90h5.  I'll close this.

**Closed as completed by home4slc** 2016-02-22 19:19 UTC
Labels: bug
